name: wine-jfc
on: [push]
jobs:
  train-model:
    runs-on: [self-hosted, cml-gpu]
    container: ghcr.io/iterative/cml:0-dvc2-base1
    steps:
      - uses: actions/checkout@v3
      # Aquí se omiten las acciones de configuración de Node y Python, 
      # asumiendo que el contenedor ya tiene lo necesario.
      # Si no es así, descomenta y ajusta las siguientes líneas:
      # - uses: actions/setup-node@v3
      #   with:
      #     node-version: '16'
      # - uses: actions/setup-python@v4
      #   with:
      #     python-version: '3.x'
      - uses: iterative/setup-cml@v1
      - name: cml_run
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Tu flujo de trabajo de ML va aquí
          pip install -r requirements.txt
          python train.py
          
          echo "METRICAS DEL MODELO"
          cat metrics.json
